In [1]:
import pandas as pd
import numpy as np
data = {
    'Tr_ID': [101, 102, 103, 103, 105, 106, 107, 108, 109, 110],
    'Tarix': ['2026-05-01', '2026-05-02', '2026/05/03', '2026-05-03', '2026-05-05', '2026-05-06', None, '2026-05-08', '2026-05-09', '2026-05-10'],
    'Mehsul_Kateqoriyasi': ['Elektronika', ' geyim ', 'Elektronika', 'Elektronika', 'Məişət', 'Geyim', 'Elektronika', 'Məişət', None, 'Geyim'],
    'Satilan_Say': [2, -5, 1, 1, 3, None, 5, 2, 4, 1],
    'Vahid_Qiymet': [150, 40, 200, 200, 80, 50, 120, None, 30, 60],
    'Region': ['Bakı', 'Gəncə', 'Bakı', 'Bakı', 'Sumqayıt', 'Bakı', 'Gəncə', 'Sumqayıt', 'Bakı', 'Bakı']
}
df = pd.DataFrame(data)
df

   Tr_ID       Tarix Mehsul_Kateqoriyasi  Satilan_Say  Vahid_Qiymet    Region
0    101  2026-05-01         Elektronika          2.0         150.0      Bakı
1    102  2026-05-02              geyim          -5.0          40.0     Gəncə
2    103  2026/05/03         Elektronika          1.0         200.0      Bakı
3    103  2026-05-03         Elektronika          1.0         200.0      Bakı
4    105  2026-05-05              Məişət          3.0          80.0  Sumqayıt
5    106  2026-05-06               Geyim          NaN          50.0      Bakı
6    107        None         Elektronika          5.0         120.0     Gəncə
7    108  2026-05-08              Məişət          2.0           NaN  Sumqayıt
8    109  2026-05-09                None          4.0          30.0      Bakı
9    110  2026-05-10               Geyim          1.0          60.0      Bakı

In [13]:
print("---Təmizlənmiş data---")
df = df.drop_duplicates(subset=['Tr_ID'])
df = df.dropna(subset=['Tarix', 'Mehsul_Kateqoriyasi','Tr_ID'])

df['Tarix'] = pd.to_datetime(df['Tarix'], format='mixed')
df['Mehsul_Kateqoriyasi']=df['Mehsul_Kateqoriyasi'].str.strip().str.capitalize()
df['Satilan_Say']=df['Satilan_Say'].clip(1,100).fillna(1).astype(int)
vahid_qiymet_ortalama=np.nanmedian(df['Vahid_Qiymet'])
df['Vahid_Qiymet']=df['Vahid_Qiymet'].fillna(vahid_qiymet_ortalama)
df

---Təmizlənmiş data---

,Tr_ID,Tarix,Mehsul_Kateqoriyasi,Satilan_Say,Vahid_Qiymet,Region,Gelir
0,101,2026-05-01,Elektronika,2,150.0,Bakı,300.0
1,102,2026-05-02,Geyim,1,40.0,Gəncə,40.0
2,103,2026-05-03,Elektronika,1,200.0,Bakı,200.0
4,105,2026-05-05,Məişət,3,80.0,Sumqayıt,240.0
5,106,2026-05-06,Geyim,1,50.0,Bakı,50.0
7,108,2026-05-08,Məişət,2,70.0,Sumqayıt,140.0
9,110,2026-05-10,Geyim,1,60.0,Bakı,60.0

In [14]:
print("---Filtrləmə---")
a=df[(df['Region']=='Bakı') & (df['Vahid_Qiymet']>100)]
print("Bakı regionunda vahid qiyməti 100-dən çox olan məhsullar:")
a

---Filtrləmə---
Bakı regionunda vahid qiyməti 100-dən çox olan məhsullar:

,Tr_ID,Tarix,Mehsul_Kateqoriyasi,Satilan_Say,Vahid_Qiymet,Region,Gelir
0,101,2026-05-01,Elektronika,2,150.0,Bakı,300.0
2,103,2026-05-03,Elektronika,1,200.0,Bakı,200.0

In [15]:
print("---Yeni sütun yaratma---")
df['Gelir']=df['Satilan_Say']*df['Vahid_Qiymet']
print("Gəlir sütunu əlavə edilmiş data:")
df

---Yeni sütun yaratma---
Gəlir sütunu əlavə edilmiş data:

,Tr_ID,Tarix,Mehsul_Kateqoriyasi,Satilan_Say,Vahid_Qiymet,Region,Gelir
0,101,2026-05-01,Elektronika,2,150.0,Bakı,300.0
1,102,2026-05-02,Geyim,1,40.0,Gəncə,40.0
2,103,2026-05-03,Elektronika,1,200.0,Bakı,200.0
4,105,2026-05-05,Məişət,3,80.0,Sumqayıt,240.0
5,106,2026-05-06,Geyim,1,50.0,Bakı,50.0
7,108,2026-05-08,Məişət,2,70.0,Sumqayıt,140.0
9,110,2026-05-10,Geyim,1,60.0,Bakı,60.0

In [16]:
print("---Qruplaşdırma---")
b=df.groupby('Mehsul_Kateqoriyasi').agg({'Satilan_Say': 'sum', 'Gelir': 'sum'})
print(b)

---Qruplaşdırma---
                     Satilan_Say  Gelir
Mehsul_Kateqoriyasi
Elektronika                    3  500.0
Geyim                          3  150.0
Məişət                         5  380.0